// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entities

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE0c3566dDecodeGithubComBurnbSignallerInternalRepositoryEntities(in *jlexer.Lexer, out *Position) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "symbol":
			out.Symbol = string(in.String())
		case "entryPrice":
			out.EntryPrice = float64(in.Float64())
		case "pnl":
			out.Pnl = float64(in.Float64())
		case "roe":
			out.Roe = float64(in.Float64())
		case "amount":
			out.Amount = float64(in.Float64())
		case "leverage":
			out.Leverage = uint8(in.Uint8())
		case "createTimeStamp":
			out.CreateTimestamp = int64(in.Int64())
		case "updateTimeStamp":
			out.UpdateTimestamp = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE0c3566dEncodeGithubComBurnbSignallerInternalRepositoryEntities(out *jwriter.Writer, in Position) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"entryPrice\":"
		out.RawString(prefix)
		out.Float64(float64(in.EntryPrice))
	}
	{
		const prefix string = ",\"pnl\":"
		out.RawString(prefix)
		out.Float64(float64(in.Pnl))
	}
	{
		const prefix string = ",\"roe\":"
		out.RawString(prefix)
		out.Float64(float64(in.Roe))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.Float64(float64(in.Amount))
	}
	{
		const prefix string = ",\"leverage\":"
		out.RawString(prefix)
		out.Uint8(uint8(in.Leverage))
	}
	{
		const prefix string = ",\"createTimeStamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreateTimestamp))
	}
	{
		const prefix string = ",\"updateTimeStamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.UpdateTimestamp))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Position) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE0c3566dEncodeGithubComBurnbSignallerInternalRepositoryEntities(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Position) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE0c3566dEncodeGithubComBurnbSignallerInternalRepositoryEntities(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Position) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE0c3566dDecodeGithubComBurnbSignallerInternalRepositoryEntities(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Position) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE0c3566dDecodeGithubComBurnbSignallerInternalRepositoryEntities(l, v)
}
