// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entities

import (
	sql "database/sql"
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE0c3566dDecodeGithubComBurnbSignallerInternalRepositoryEntities(in *jlexer.Lexer, out *Position) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Id":
			out.Id = int64(in.Int64())
		case "TraderUID":
			out.TraderUID = string(in.String())
		case "symbol":
			out.Symbol = string(in.String())
		case "entryPrice":
			out.EntryPrice = float64(in.Float64())
		case "Pnl":
			out.Pnl = float64(in.Float64())
		case "Roe":
			out.Roe = float64(in.Float64())
		case "Amount":
			out.Amount = float64(in.Float64())
		case "Invested":
			out.Invested = float64(in.Float64())
		case "Leverage":
			out.Leverage = uint8(in.Uint8())
		case "createTimestamp":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updateTimestamp":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		case "closedTimestamp":
			easyjsonE0c3566dDecodeDatabaseSql(in, &out.ClosedAt)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE0c3566dEncodeGithubComBurnbSignallerInternalRepositoryEntities(out *jwriter.Writer, in Position) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Id))
	}
	{
		const prefix string = ",\"TraderUID\":"
		out.RawString(prefix)
		out.String(string(in.TraderUID))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"entryPrice\":"
		out.RawString(prefix)
		out.Float64(float64(in.EntryPrice))
	}
	{
		const prefix string = ",\"Pnl\":"
		out.RawString(prefix)
		out.Float64(float64(in.Pnl))
	}
	{
		const prefix string = ",\"Roe\":"
		out.RawString(prefix)
		out.Float64(float64(in.Roe))
	}
	{
		const prefix string = ",\"Amount\":"
		out.RawString(prefix)
		out.Float64(float64(in.Amount))
	}
	{
		const prefix string = ",\"Invested\":"
		out.RawString(prefix)
		out.Float64(float64(in.Invested))
	}
	{
		const prefix string = ",\"Leverage\":"
		out.RawString(prefix)
		out.Uint8(uint8(in.Leverage))
	}
	{
		const prefix string = ",\"createTimestamp\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updateTimestamp\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"closedTimestamp\":"
		out.RawString(prefix)
		easyjsonE0c3566dEncodeDatabaseSql(out, in.ClosedAt)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Position) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE0c3566dEncodeGithubComBurnbSignallerInternalRepositoryEntities(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Position) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE0c3566dEncodeGithubComBurnbSignallerInternalRepositoryEntities(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Position) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE0c3566dDecodeGithubComBurnbSignallerInternalRepositoryEntities(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Position) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE0c3566dDecodeGithubComBurnbSignallerInternalRepositoryEntities(l, v)
}
func easyjsonE0c3566dDecodeDatabaseSql(in *jlexer.Lexer, out *sql.NullTime) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Time":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Time).UnmarshalJSON(data))
			}
		case "Valid":
			out.Valid = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE0c3566dEncodeDatabaseSql(out *jwriter.Writer, in sql.NullTime) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Time\":"
		out.RawString(prefix[1:])
		out.Raw((in.Time).MarshalJSON())
	}
	{
		const prefix string = ",\"Valid\":"
		out.RawString(prefix)
		out.Bool(bool(in.Valid))
	}
	out.RawByte('}')
}
