// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: signaller_api.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_LONG  Direction = 0
	Direction_SHORT Direction = 1
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "LONG",
		1: "SHORT",
	}
	Direction_value = map[string]int32{
		"LONG":  0,
		"SHORT": 1,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_signaller_api_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_signaller_api_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_signaller_api_proto_rawDescGZIP(), []int{0}
}

type Command int32

const (
	Command_CREATE Command = 0
	Command_UPDATE Command = 1
	Command_CLOSE  Command = 2
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "CLOSE",
	}
	Command_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"CLOSE":  2,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_signaller_api_proto_enumTypes[1].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_signaller_api_proto_enumTypes[1]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_signaller_api_proto_rawDescGZIP(), []int{1}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []string `protobuf:"bytes,1,rep,name=Uids,proto3" json:"Uids,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signaller_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaller_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_signaller_api_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

type PositionEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol     string               `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Uid        string               `protobuf:"bytes,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Direction  Direction            `protobuf:"varint,3,opt,name=Direction,proto3,enum=signaller.Direction" json:"Direction,omitempty"`
	PositionId int64                `protobuf:"varint,4,opt,name=PositionId,proto3" json:"PositionId,omitempty"`
	Command    Command              `protobuf:"varint,5,opt,name=Command,proto3,enum=signaller.Command" json:"Command,omitempty"`
	Exchange   string               `protobuf:"bytes,6,opt,name=Exchange,proto3" json:"Exchange,omitempty"`
	Leverage   uint32               `protobuf:"varint,7,opt,name=Leverage,proto3" json:"Leverage,omitempty"`
	EntryPrice float64              `protobuf:"fixed64,8,opt,name=EntryPrice,proto3" json:"EntryPrice,omitempty"`
	CreatedAt  *timestamp.Timestamp `protobuf:"bytes,9,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Hedged     bool                 `protobuf:"varint,10,opt,name=Hedged,proto3" json:"Hedged,omitempty"`
}

func (x *PositionEvent) Reset() {
	*x = PositionEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signaller_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionEvent) ProtoMessage() {}

func (x *PositionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_signaller_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionEvent.ProtoReflect.Descriptor instead.
func (*PositionEvent) Descriptor() ([]byte, []int) {
	return file_signaller_api_proto_rawDescGZIP(), []int{1}
}

func (x *PositionEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionEvent) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PositionEvent) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_LONG
}

func (x *PositionEvent) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *PositionEvent) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_CREATE
}

func (x *PositionEvent) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *PositionEvent) GetLeverage() uint32 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

func (x *PositionEvent) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *PositionEvent) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PositionEvent) GetHedged() bool {
	if x != nil {
		return x.Hedged
	}
	return false
}

var File_signaller_api_proto protoreflect.FileDescriptor

var file_signaller_api_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x6c, 0x65, 0x72,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x26, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x55, 0x69, 0x64, 0x73, 0x22, 0xe5, 0x02, 0x0a, 0x0d, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x4c, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x64,
	0x67, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x48, 0x65, 0x64, 0x67, 0x65,
	0x64, 0x2a, 0x20, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08,
	0x0a, 0x04, 0x4c, 0x4f, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x48, 0x4f, 0x52,
	0x54, 0x10, 0x01, 0x2a, 0x2c, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50,
	0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10,
	0x02, 0x32, 0x53, 0x0a, 0x0c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x41, 0x70,
	0x69, 0x12, 0x43, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1b, 0x2e, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x22, 0x00, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_signaller_api_proto_rawDescOnce sync.Once
	file_signaller_api_proto_rawDescData = file_signaller_api_proto_rawDesc
)

func file_signaller_api_proto_rawDescGZIP() []byte {
	file_signaller_api_proto_rawDescOnce.Do(func() {
		file_signaller_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_signaller_api_proto_rawDescData)
	})
	return file_signaller_api_proto_rawDescData
}

var file_signaller_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_signaller_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_signaller_api_proto_goTypes = []interface{}{
	(Direction)(0),              // 0: signaller.Direction
	(Command)(0),                // 1: signaller.Command
	(*SubscribeRequest)(nil),    // 2: signaller.SubscribeRequest
	(*PositionEvent)(nil),       // 3: signaller.PositionEvent
	(*timestamp.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_signaller_api_proto_depIdxs = []int32{
	0, // 0: signaller.PositionEvent.Direction:type_name -> signaller.Direction
	1, // 1: signaller.PositionEvent.Command:type_name -> signaller.Command
	4, // 2: signaller.PositionEvent.CreatedAt:type_name -> google.protobuf.Timestamp
	2, // 3: signaller.SignallerApi.Stream:input_type -> signaller.SubscribeRequest
	3, // 4: signaller.SignallerApi.Stream:output_type -> signaller.PositionEvent
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_signaller_api_proto_init() }
func file_signaller_api_proto_init() {
	if File_signaller_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_signaller_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signaller_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_signaller_api_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signaller_api_proto_goTypes,
		DependencyIndexes: file_signaller_api_proto_depIdxs,
		EnumInfos:         file_signaller_api_proto_enumTypes,
		MessageInfos:      file_signaller_api_proto_msgTypes,
	}.Build()
	File_signaller_api_proto = out.File
	file_signaller_api_proto_rawDesc = nil
	file_signaller_api_proto_goTypes = nil
	file_signaller_api_proto_depIdxs = nil
}
