version: '3.8'

services:
  db:
    image: mysql:8
    container_name: signaller.db
    hostname: signaller.db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mysql/conf.d:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - signaller
    restart: unless-stopped

networks:
  signaller:
    driver: bridge