// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package metric

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6a975c40DecodeGithubComBurnbSignallerInternalMetric(in *jlexer.Lexer, out *Main) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Uptime":
			out.Uptime = string(in.String())
		case "LastEventAt":
			out.LastEventAt = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeGithubComBurnbSignallerInternalMetric(out *jwriter.Writer, in Main) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Uptime\":"
		out.RawString(prefix[1:])
		out.String(string(in.Uptime))
	}
	{
		const prefix string = ",\"LastEventAt\":"
		out.RawString(prefix)
		out.String(string(in.LastEventAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Main) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeGithubComBurnbSignallerInternalMetric(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Main) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeGithubComBurnbSignallerInternalMetric(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Main) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeGithubComBurnbSignallerInternalMetric(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Main) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeGithubComBurnbSignallerInternalMetric(l, v)
}
